#!/bin/bash

# This script can only connect to WPA networks with a key. 
# Use ManageOpen for networks without a key.
# In general, for known networks, just do "Manage <SSID> <Key>"

INTERFACE=$(iw dev | awk '/Interface/ {print $2}')
PerformConnect() {
    echo "Bringing interface up, scanning..."
    sudo ifconfig $INTERFACE down
    sudo ifconfig $INTERFACE up
    sudo iwlist $INTERFACE scan > /dev/null

    echo "Starting WPA_Supplicant."
        sudo wpa_supplicant -i$INTERFACE -c "$1" &
        echo "Sleeping for 3 seconds."
        sleep 3
        echo "Starting dhclient."
        sudo dhclient $INTERFACE
}

CONDIR=$HOME/.connections
mkdir -p $CONDIR

if [[ "$#" = 1 ]]; then
if [[ ! -e $CONDIR/${1}.conf ]]; then
echo "Do not already have a configuration for this WPA network."
echo "Please run with  a password the first time."
exit
fi
# Here we assume we did not exit, so there exists a WPA network we are managing.
# Note that this script would have run with SetUID 1.
PerformConnect "$CONDIR/${1}.conf"

elif [[ "$#" = 2 ]]; then
    echo "Overwriting current configuration for network $1"
    wpa_passphrase "$1" "$2" > "$CONDIR/${1}.conf"
    PerformConnect "$CONDIR/${1}.conf"
fi
